### ISSUE TITLE
Repository under Open Oakland

### ISSUE THREAD

**Issue by TangoYankee** [clintonb/cookiecutter-django#14]
## Description
It appears this project is intended to be a tool for Open Oaklanders to develop their projects. Volunteers should be able to find it in a location owned by the organization.

## Request
Have the [OpenOakland github organization](https://github.com/openoakland/) contain either a base or forked version of the repository, once it has matured.

**Comment by clintonb** [comment]
Feel free to fork the repo to Open Oakland. I prefer to maintain control over this project.
